import { useState, Fragment } from "react";
import Head from "next/head";
import Image from "next/image";
import { Disclosure } from "@headlessui/react";
import SlickSlider from "react-slick";
import ReactStars from "react-rating-stars-component";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

import ProductCard from "../../components/ProductCard/ProductCard";
import styles from "../../styles/details.module.scss";

const Arrow = ({ className, onClick, image, customClass }) => (
  <div onClick={onClick} className={`${className} ${styles["slick-arrow"]} ${customClass ?? ''}`}>
    <img className="z-10" src={image} alt="arrows" />
  </div>
);

const ProductDetails = () => {
  const [quantity, setQuantity] = useState(0);
  const settingsMain = {
    dots: false,
    infinite: true,
    slidesToShow: 1,
    slidesToScroll: 1,
    arrow: false,
    autoplay: false,
  };
  const settingsThumbnail = {
    dots: false,
    infinite: true,
    slidesToShow: 3,
    slidesToScroll: 1,
    arrow: false,
    nextArrow: <Arrow customClass={styles["next-arrow"]} image="/images/product-thumb-next.svg" />,
    prevArrow: <Arrow image="/images/product-thumb-prev.svg" />,
  };
  const product_images = ["/images/sample/slider-post-one.jpg", "/images/sample/slider-post-one.jpg", "/images/sample/slider-post-one.jpg"];
  const thumbnails = [
    "/images/sample/slide-thumb1.jpg",
    "/images/sample/slide-thumb2.jpg",
    "/images/sample/slide-thumb3.jpg",
    "/images/sample/slide-thumb1.jpg",
    "/images/sample/slide-thumb2.jpg",
    "/images/sample/slide-thumb3.jpg",
  ];

  const changeQuantity = (adder) => {
    // @TODO: add max value limit
    if (quantity == 0 && adder < 0) return;
    setQuantity(quantity + adder);
  };

  return (
    <Fragment>
      <Head>
        <title>Product | Craftezy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="wrapper">
        <section className={styles["product-detail-section"]}>
          <div className={styles["product-detail-wrap"]}>
            <div className={`${styles["product-detail-main"]} flex`}>
              <div className={styles["product-detail-image"]}>
                <SlickSlider className={`${styles["product-slider-for"]} ${styles["slider-for"]}`} {...settingsMain}>
                  {product_images.map((image) => (
                    <div className={styles["detail-slide-for"]}>
                      <figure className={styles["slide-for-image"]}>
                        <img src={image} alt="slider-post-one" />
                      </figure>
                    </div>
                  ))}
                </SlickSlider>
                <SlickSlider className={`${styles["product-slider-nav"]} ${styles["slider-nav"]}`} {...settingsThumbnail}>
                  {thumbnails.map((image) => (
                    <div className={styles["detail-slide-nav"]}>
                      <figure className={styles["slide-nav-image"]}>
                        <img src={image} alt="slide-thumb" />
                      </figure>
                    </div>
                  ))}
                </SlickSlider>
              </div>
              <div className={styles["product-detail-text"]}>
                <div className={styles["product-detail-title"]}>
                  <h1>Bamboo Mira Squircle Mirror</h1>
                  <p>Log in or create account to view Wholesale price</p>
                </div>
                <div className={styles["product-reviews"]}>
                  <div className={styles["ratings"]}>
                    <ReactStars value={5} count={5} onChange={() => {}} size={25} activeColor="#FB8200" />
                  </div>
                  <span className={styles["total"]}>
                    5.0 out of (1256) <a href="#">Reviews</a>
                  </span>
                  <p>Log in or create account to view Wholesale price</p>
                </div>
                <div className={styles["product-story"]}>
                  <h5>Story</h5>
                  <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque nec consequat lorem. Maecenas elementum at diam
                    consequat bibendum. Mauris iaculis fringilla ex, sit amet semper libero facilisis sit amet. Nunc ut aliquet metus.{" "}
                  </p>
                </div>
                <div className={styles["product-impact"]}>
                  <h5>Impact</h5>
                  <ul className={`${styles["product-icons"]} flex`}>
                    <li>
                      <a href="/">
                        <img src="/images/icon-park.svg" alt="icon" />
                      </a>
                    </li>
                    <li>
                      <a href="/">
                        <img src="/images/icon-park.svg" alt="icon" />
                      </a>
                    </li>
                    <li>
                      <a href="/">
                        <img src="/images/icon-park.svg" alt="icon" />
                      </a>
                    </li>
                    <li>
                      <a href="/">
                        <img src="/images/icon-park.svg" alt="icon" />
                      </a>
                    </li>
                    <li>
                      <a href="/">
                        <img src="/images/icon-park.svg" alt="icon" />
                      </a>
                    </li>
                  </ul>
                </div>
                <div className={styles["product-Quantity"]}>
                  <h5>Item Quantity</h5>
                  <div className={`${styles["product-price"]} flex items-center`}>
                    <img onClick={() => changeQuantity(-1)} src="/images/ant-design_minus-outlined.svg" alt="minus" />
                    <div className={styles["price-number"]}>{quantity}</div>
                    <img onClick={() => changeQuantity(+1)} src="/images/ant-design_plus-outlined.svg" alt="plus" />
                  </div>
                </div>
                <div className={styles["product-button"]}>
                  <a href="/" className={styles["button"]}>
                    Add to Cart
                  </a>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section className={styles["product-detail-section"]}>
          <div className="">
            <div className={styles["accordion-main"]}>
              <Disclosure>
                {({ open }) => (
                  <div className={`${styles["ui-accordion"]}`}>
                    <Disclosure.Button as="h3" className={`${styles["ui-accordion-header"]} ${open ? styles["ui-state-active"] : ""}`}>
                      <span>Specifications</span>
                      <img
                        onClick={() => changeQuantity(-1)}
                        src={open ? "/images/ant-design_minus-outlined.svg" : "/images/ant-design_plus-outlined.svg"}
                        alt="minus"
                      />
                    </Disclosure.Button>
                    <Disclosure.Panel className={styles["ui-accordion-content"]}>
                      <table>
                        <tr>
                          <td>Category:</td>
                          <td>Mirrors</td>
                        </tr>
                        <tr>
                          <td>Origin:</td>
                          <td>India</td>
                        </tr>
                        <tr>
                          <td>Composition:</td>
                          <td>Bamboo, Mirror</td>
                        </tr>
                        <tr>
                          <td>Dimensions:</td>
                          <td>450(Width), 600(H) X 60(D); 450(W), 1200(H), 60(D)</td>
                        </tr>
                        <tr>
                          <td>Ships from:</td>
                          <td>India</td>
                        </tr>
                        <tr>
                          <td>Item Sku:</td>
                          <td>AMI02LN</td>
                        </tr>
                      </table>
                    </Disclosure.Panel>
                  </div>
                )}
              </Disclosure>
              <Disclosure>
                {({ open }) => (
                  <div className={`${styles["ui-accordion"]}`}>
                    <Disclosure.Button as="h3" className={`${styles["ui-accordion-header"]} ${open ? styles["ui-state-active"] : ""}`}>
                      <span>Customization Available</span>
                      <img
                        onClick={() => changeQuantity(-1)}
                        src={open ? "/images/ant-design_minus-outlined.svg" : "/images/ant-design_plus-outlined.svg"}
                        alt="minus"
                      />
                    </Disclosure.Button>

                    <Disclosure.Panel className={styles["ui-accordion-content"]}>
                      <ul>
                        <li>
                          <strong>Colour, print &amp; size</strong>
                          <p>
                            Colour, print &amp; size: Colour, print, size, shape and form can be customised based on your requirements,
                            subject to seller MOQ. Feel free to write to us before or after placing an order.{" "}
                          </p>
                        </li>
                        <li>
                          <strong>Bulk packaging</strong>
                          <p>
                            By default, goods are bulk packaged optimally to minimize freight costs. For special packaging or private label
                            branding, feel free to write to us before or after placing an order. Branding customisation is subject to seller
                            MOQ.
                          </p>
                        </li>
                        <li>
                          <strong>Material &amp; production notes</strong>
                          <p>
                            Prices will vary with commodity price variation. This offering has been made from iron and touts a rustic
                            aesthetic. Any minor irregularities in colour or polish are part of the handmade charm. These attributes lend a
                            unique flavour to the offering, making it exclusive.
                          </p>
                        </li>
                      </ul>
                    </Disclosure.Panel>
                  </div>
                )}
              </Disclosure>
            </div>
          </div>
        </section>
        <section className={styles["product-seller-section"]}>
          <div className={styles["product-seller-main"]}>
            <div className={`${styles["product-seller-title"]} text-center`}>
              <h2>More from this seller</h2>
            </div>

            <div className="my-10 grid md:grid-cols-3 sm:grid-cols-2 grid-cols-1 gap-x-3 gap-y-8">
              <ProductCard />
              <ProductCard />
              <ProductCard />
            </div>
          </div>
        </section>
      </main>
    </Fragment>
  );
};

export default ProductDetails;
