import { useState, Fragment } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/blogCategories.module.scss";

const Categories = () => {
  return (
    <Fragment>
      <Head>
        <title>Blogs | Craftezy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className={`${styles["blog-categorization-section"]} relative`}>
          <picture className={styles["background-bg"]}>
            <img src="/images/blog-categorization-banner.jpg" alt="blog-categorization-banner" />
          </picture>
          <div className="wrapper">
            <div className={`${styles["blog-categorization-main"]} flex items-center justify-center`}>
              <div className={styles["blog-categorization-text"]}>
                <h1>Craftezy's Blog</h1>
              </div>
            </div>
          </div>
        </section>

        <section className={styles["sellers-buyers-section"]}>
          <div className="wrapper">
            <div className={styles["sellers-buyers-main"]}>
              <div className={`${styles["sellers-buyers-list"]} text-center`}>
                <h2>For Sellers</h2>
                <div className={styles["sellers-buyers-pos"]}>
                  <figure className={`${styles["sellers-buyers-image"]} object-fit`}>
                    <img src="/images/sellers.jpg" alt="sellers" />
                  </figure>
                  <div className={styles["sellers-buyers-text"]}>
                    <h3>Sellers</h3>
                    <p>
                      Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's
                      standard
                    </p>
                  </div>
                </div>
              </div>
              <div className={`${styles["sellers-buyers-list"]} text-center`}>
                <h2>For Buyers</h2>
                <div className={styles["sellers-buyers-pos"]}>
                  <figure className={`${styles["sellers-buyers-image"]} object-fit`}>
                    <img src="/images/buyers.jpg" alt="buyers" />
                  </figure>
                  <div className={styles["sellers-buyers-text"]}>
                    <h3>Buyers</h3>
                    <p>
                      Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's
                      standard
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </Fragment>
  );
};

export default Categories;
